type Config = { js: string; ts: string };

// ? App dir
const RootLayout: Config = {
  ts: `import type { Metadata } from "next";
import { Inter as FontSans } from "next/font/google";
import { cn } from "ALIAS/lib/utils";

import "./globals.css";

export const metadata: Metadata = {
  title: "Kepa's Next Starter",
  description: "Generated by Kepa's Next Starter",
};

const fontSans = FontSans({
  subsets: ["latin"],
  variable: "--font-sans",
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <head />
      <body className={cn("min-h-screen bg-background font-sans antialiased", GeistSans.variable)}>{children}</body>
    </html>
  );
}`,
  js: `import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  );
}`,
};

const _App: Config = {
  ts: `import { cn } from "ALIAS/lib/utils";
import "ALIAS/styles/globals.css";
import type { AppProps } from "next/app";
import { Inter as FontSans } from "next/font/google";

const fontSans = FontSans({
  subsets: ["latin"],
  variable: "--font-sans",
});

export default function App({ Component, pageProps }: AppProps) {
  return (
    <main className={cn("min-h-screen bg-background font-sans antialiased", fontSans.variable)}>
      <Component {...pageProps} />
    </main>
  );
}`,

  js: `import { cn } from "ALIAS/lib/utils";
import "ALIAS/styles/globals.css";
import { Inter as FontSans } from "next/font/google";

const fontSans = FontSans({
  subsets: ["latin"],
  variable: "--font-sans",
});

export default function App({ Component, pageProps }) {
  return (
    <main className={cn("min-h-screen bg-background font-sans antialiased", fontSans.variable)}>
      <Component {...pageProps} />
    </main>
  );
}`,
};

export { RootLayout, _App };
