name: Deploy api

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: self-hosted
    environment: production
    strategy:
      matrix:
        node-version: [20.12.0]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install Bun
        run: |
          curl -fsSL https://bun.sh/install | bash
          export BUN_INSTALL="$HOME/.bun"
          export PATH="$BUN_INSTALL/bin:$PATH"
      
      - name: Run deployment commands
        run: |
          cd /home/ubuntu
          rm -rf next-starter-api
          git clone https://github.com/Piarre/next-starter-api
          cd next-starter-api
          touch start.sh && echo "bun run dist/index.js" >> start.sh
          bun install
          bun build
          pm2 start ./start.sh --name "next-starter-api"