name: Deploy API

on:
  push:
    branches:
      - "**"
  workflow_call:

jobs:
  deploy:
    environment: production
    permissions: write-all
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
      - name: Install dependencies
        run: bun install
        env:
          CI: true
      - name: Build
        run: bun run build
        env:
          CI: true
      - name: Publish Docker Image
        uses: elgohr/Publish-Docker-Github-Action@v4
        with:
          name: piarre/next-starter-api
          registry: ghcr.io
          username: piarre
          password: ${{ secrets.GITHUB_TOKEN }}
          dockerfile: Dockerfile
          tags: latest
      - name: Deploy and run new image
        env:
          CI: true
          GITHUB_USERNAME: piarre
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          export CONTAINER_NAME=$(docker ps -a -q --filter "name=next-starter-api")

          if [ -z "$CONTAINER_NAME" ]; then
            CONTAINER_NAME="next-starter-api"
          fi

          docker login ghcr.io -u $GITHUB_USERNAME -p $GITHUB_TOKEN
          docker pull ghcr.io/piarre/next-starter-api:latest
          docker stop $CONTAINER_NAME && docker rm $CONTAINER_NAME || true
          docker run -dit \
            --restart=always \
            --name next-starter-api \
            --network proxy \
            -p 2025:2025 \
            --label traefik.enable=true \
            --label traefik.http.routers.next-starter-api.entrypoints=websecure \
            --label traefik.http.routers.next-starter-api.rule="Host(\`next-starter-api.piarre.app\`)" \
            --label traefik.http.routers.next-starter-api.tls.certresolver=myresolver \
            --label traefik.http.services.next-starter-api.loadbalancer.server.port=2025 \
            ghcr.io/piarre/next-starter-api:latest
